### PR TITLE
Add bicubic resize for RGB images

### LINKED ISSUE #9: RESIZE: allow custom interpolation
I'd like to modify `resize` to allow for non-nearest-neighbor interpolation (e.g. bicubic), but the API for the generic function does not currently permit any kind of optional or keyword parameters.

I propose adding `&key (interpolation 'imago:nearest-neighbor)` to the lambda list and supplying the appropriate implementation for `imago:nearest-neighbor`, and then adding more interpolation schemes as fit.

How does that sound?

### PR DESCRIPTION
**Pull request by phoe**
This closes #9 by adding cubic interpolation option to `resize` (currently only implemented for RGB images - TODO for everything else).

This implementation is ~~slow and conses like crazy (a little bit less now after optimization)~~ sorta optimized now.

```lisp
CL-USER> (let* ((image (imago:read-png "~/Downloads/hatsu2.png")))
           (time (imago:resize image 900 1200 :interpolation :bicubic)))
Evaluation took:
  0.319 seconds of real time
  0.321307 seconds of total run time (0.321282 user, 0.000025 system)
  100.63% CPU
  1,124,300,583 processor cycles
  4,320,016 bytes consed
```

But I want to get the algorithm correct and pin it with some test cases before I start optimizing it away. Are there any test suites for image resizing with bicubic interpolation that you are aware of? If you have some time and energy, are you willing to give it a spin on your own?

------------

Showcase:

Original:
hatsu2

`(imago:resize image 150 200 :interpolation 'imago:bicubic)` (shrunk):
test11

`(imago:resize image 900 1200 :interpolation 'imago:bicubic)` (enlarged):
test10

### CODE REVIEW

**Comment by shamazmazum** [comment]
Hello. I am doing a bit of work on it myself after your issue. I think I'll ask to modify your request a bit after I am done.

I think it will simplify adding different interpolation methods in the future.

**Comment by shamazmazum** [comment]
I did what I planned.

Can you rewrite your contribution so it adds a new `interpolate-pixel` method which takes an image and coordinates `(x, y)` in `(single-float 0f0 1f0)` format, where zero means upper left and one means lower right corners of the image?

When you do so, you will be able to call `(resize image new-width new-height :interpolation :your-new-interpolation-method)`.

**Comment by phoe** [comment]
OK, thanks - I'll spend a short while on making the algorithm a little bit more acceptable time-wise and I'll rebase to your current master.

Should interpolation methods be named after keywords or external symbols in the `imago` package?

**Comment by shamazmazum** [comment]
> Should interpolation methods be named after keywords or external symbols in the imago package?

IMHO, symbols from `keword` package are better suited for this purpose.

**Comment by phoe** [comment]
OK, the resize is now 20 times not as damn slow as before. Let me update to the new API of yours.

**Comment by phoe** [comment]
Fully rebased and ready for review.

Performance is still slow but a little bit better; I think that any future improvement will require indulging in some vector operations unless I badly missed something in the algorithm.

```lisp
CL-USER> (let* ((image (imago:read-png "~/Downloads/hatsu2.png")))
           (time (imago:resize image 900 1200 :interpolation :bicubic)))
Evaluation took:
  0.319 seconds of real time
  0.321307 seconds of total run time (0.321282 user, 0.000025 system)
  100.63% CPU
  1,124,300,583 processor cycles
  4,320,016 bytes consed
  
#<IMAGO:RGB-IMAGE (900x1200) {1011370C33}>
```

**Comment by phoe** [comment]
TODO: use `alex:array-index` as a type for array indices.

**Comment by shamazmazum** [comment]
Thanks! Few things to fix before merging.

1) Can you please use `git reset` and/or `git rebase` to produce one or two commits which are easier to review? You can force-push then.
2) I renamed `:linear` to `:bilinear` as you asked, this PR seems to rename it back.
3) Please do not operate with pixels as if they were mere integers (even if they really are). Do not call `ash`, `ldb`, `logfoo` on them. Use pixel constructors `make-gray`, `make-color` and accessors `color-red`, `color-green`, etc. and `gray-intensity`, `gray-alpha`. These functions are there for a reason, after all :)
If I am right, you can call interpolation function for each pixel component independently using an accessor and then construct a pixel using a constructor.

**Comment by phoe** [comment]
1. Done - squashed all commits into one.
2. Thanks for the catch! Fixed.
3. OK, I'll try to restructure my code.

**Comment by phoe** [comment]
Requested change no. 3 results in a 60% slowdown (~300ms vs ~500ms on my test file). Are you sure you want to require me to stick to accessor functions for an operation that is already rather slow for an image operation?

Old version (byte munging):

```lisp
CL-USER> (let* ((image (imago:read-png "~/Downloads/hatsu2.png"))) 
           (the-cost-of-nothing:bench
            (imago:resize image 900 1200 :interpolation :bicubic)))
294.10 milliseconds
; No value
```

New version (accessors):

```lisp
CL-USER> (let* ((image (imago:read-png "~/Downloads/hatsu2.png"))) 
           (the-cost-of-nothing:bench
            (imago:resize image 900 1200 :interpolation :bicubic)))
489.99 milliseconds
; No value
```

The changed Lisp code:

```lisp
(defun interpolate-pixel-cubic (image x y constructor accessors)
  (declare (optimize speed (debug 0)))
  (declare (type (single-float 0f0 1f0) x y))
  (declare (type function constructor))
  (with-image-definition (image width height image-pixels)
    (declare (type (unsigned-byte 32) height width))
    (declare (type (simple-array (unsigned-byte 32) (* *)) image-pixels))
    (let ((x (- (* x width) 0.5f0))
          (y (- (* y height) 0.5f0)))
      (declare (type (single-float -10f10 10f10) x y))
      (labels ((compute-neighborhood (real-y real-x neighborhood)
                 (declare (inline clamp))
                 (dotimes (i (length +resize-offsets+))
                   (let* ((cell (aref +resize-offsets+ i))
                          (offset-y (car cell))
                          (offset-x (cdr cell)))
                     (declare (type (signed-byte 8) offset-x offset-y))
                     (let ((y (ldb (byte 32 0) (+ real-y offset-y)))
                           (x (ldb (byte 32 0) (+ real-x offset-x))))
                       (setf (aref neighborhood i)
                             (aref image-pixels
                                   (clamp y 0 (1- height))
                                   (clamp x 0 (1- width))))))))
               (cubic (x p0 p1 p2 p3)
                 (declare (type single-float x p0 p1 p2 p3))
                 (let* ((step1 (* x (+ (* 3f0 (- p1 p2)) p3 (- p0))))
                        (step2 (* x (+ (* 2f0 p0) (* -5f0 p1)
                                       (* 4f0 p2) (- p3) step1)))
                        (step3 (* x (+ p2 (- p0) step2))))
                   (+ p1 (* 0.5f0 step3))))
               (bicubic (x y pixels accessor)
                 (declare (type single-float x y))
                 (declare (type (simple-array (unsigned-byte 32) (16)) pixels))
                 (declare (type function accessor))
                 (macrolet ((px (n) `(float (the (unsigned-byte 32)
                                                 (funcall accessor (aref pixels ,n)))
                                            1f0)))
                   (let ((x1 (cubic y (px 0) (px 1) (px 2) (px 3)))
                         (x2 (cubic y (px 4) (px 5) (px 6) (px 7)))
                         (x3 (cubic y (px 8) (px 9) (px 10) (px 11)))
                         (x4 (cubic y (px 12) (px 13) (px 14) (px 15))))
                     (the (single-float -10f10 10f10) (cubic x x1 x2 x3 x4))))))
        (declare (inline compute-neighborhood cubic bicubic))
        (multiple-value-bind (real-x interp-x) (truncate x)
          (multiple-value-bind (real-y interp-y) (truncate y)
            (let ((neighborhood (make-array 16 :element-type '(unsigned-byte 32))))
              (declare (dynamic-extent neighborhood))
              (compute-neighborhood real-y real-x neighborhood)
              (flet ((access (accessor)
                       (let* ((interpolated (bicubic interp-y interp-x neighborhood accessor))
                              (clamped (clamp (round interpolated) 0 255)))
                         clamped)))
                (apply constructor (mapcar #'access accessors))))))))))

(defmethod interpolate-pixel ((image rgb-image) x y (method (eql :bicubic)))
  (interpolate-pixel-cubic image x y #'make-color
                           (list #'color-red #'color-green
                                 #'color-blue #'color-alpha)))

(defmethod interpolate-pixel ((image grayscale-image) x y (method (eql :bicubic)))
  (interpolate-pixel-cubic image x y #'make-gray
                           (list #'gray-intensity #'gray-alpha)))
```

**Comment by shamazmazum** [comment]
Do not worry about slowdown. I'll optimize what can be optimized after merging. A clean code is a priority

**Comment by shamazmazum** [comment]
Checked your algorithm. It's fine (a minor flaw that is shifts an image by few pixels, but nevermind ;) Can you please push this version and I am merging.

> Requested change no. 3 results in a 60% slowdown (~300ms vs ~500ms on my test file). Are you sure you want to require me to stick to accessor functions for an operation that is already rather slow for an image operation?
> 
> Old version (byte munging):
> 
> ```lisp
> CL-USER> (let* ((image (imago:read-png "~/Downloads/hatsu2.png"))) 
>            (the-cost-of-nothing:bench
>             (imago:resize image 900 1200 :interpolation :bicubic)))
> 294.10 milliseconds
> ; No value
> ```
> 
> New version (accessors):
> 
> ```lisp
> CL-USER> (let* ((image (imago:read-png "~/Downloads/hatsu2.png"))) 
>            (the-cost-of-nothing:bench
>             (imago:resize image 900 1200 :interpolation :bicubic)))
> 489.99 milliseconds
> ; No value
> ```
> 
> The changed Lisp code:
> 
> ```lisp
> (defun interpolate-pixel-cubic (image x y constructor accessors)
>   (declare (optimize speed (debug 0)))
>   (declare (type (single-float 0f0 1f0) x y))
>   (declare (type function constructor))
>   (with-image-definition (image width height image-pixels)
>     (declare (type (unsigned-byte 32) height width))
>     (declare (type (simple-array (unsigned-byte 32) (* *)) image-pixels))
>     (let ((x (- (* x width) 0.5f0))
>           (y (- (* y height) 0.5f0)))
>       (declare (type (single-float -10f10 10f10) x y))
>       (labels ((compute-neighborhood (real-y real-x neighborhood)
>                  (declare (inline clamp))
>                  (dotimes (i (length +resize-offsets+))
>                    (let* ((cell (aref +resize-offsets+ i))
>                           (offset-y (car cell))
>                           (offset-x (cdr cell)))
>                      (declare (type (signed-byte 8) offset-x offset-y))
>                      (let ((y (ldb (byte 32 0) (+ real-y offset-y)))
>                            (x (ldb (byte 32 0) (+ real-x offset-x))))
>                        (setf (aref neighborhood i)
>                              (aref image-pixels
>                                    (clamp y 0 (1- height))
>                                    (clamp x 0 (1- width))))))))
>                (cubic (x p0 p1 p2 p3)
>                  (declare (type single-float x p0 p1 p2 p3))
>                  (let* ((step1 (* x (+ (* 3f0 (- p1 p2)) p3 (- p0))))
>                         (step2 (* x (+ (* 2f0 p0) (* -5f0 p1)
>                                        (* 4f0 p2) (- p3) step1)))
>                         (step3 (* x (+ p2 (- p0) step2))))
>                    (+ p1 (* 0.5f0 step3))))
>                (bicubic (x y pixels accessor)
>                  (declare (type single-float x y))
>                  (declare (type (simple-array (unsigned-byte 32) (16)) pixels))
>                  (declare (type function accessor))
>                  (macrolet ((px (n) `(float (the (unsigned-byte 32)
>                                                  (funcall accessor (aref pixels ,n)))
>                                             1f0)))
>                    (let ((x1 (cubic y (px 0) (px 1) (px 2) (px 3)))
>                          (x2 (cubic y (px 4) (px 5) (px 6) (px 7)))
>                          (x3 (cubic y (px 8) (px 9) (px 10) (px 11)))
>                          (x4 (cubic y (px 12) (px 13) (px 14) (px 15))))
>                      (the (single-float -10f10 10f10) (cubic x x1 x2 x3 x4))))))
>         (declare (inline compute-neighborhood cubic bicubic))
>         (multiple-value-bind (real-x interp-x) (truncate x)
>           (multiple-value-bind (real-y interp-y) (truncate y)
>             (let ((neighborhood (make-array 16 :element-type '(unsigned-byte 32))))
>               (declare (dynamic-extent neighborhood))
>               (compute-neighborhood real-y real-x neighborhood)
>               (flet ((access (accessor)
>                        (let* ((interpolated (bicubic interp-y interp-x neighborhood accessor))
>                               (clamped (clamp (round interpolated) 0 255)))
>                          clamped)))
>                 (apply constructor (mapcar #'access accessors))))))))))
> 
> (defmethod interpolate-pixel ((image rgb-image) x y (method (eql :bicubic)))
>   (interpolate-pixel-cubic image x y #'make-color
>                            (list #'color-red #'color-green
>                                  #'color-blue #'color-alpha)))
> 
> (defmethod interpolate-pixel ((image grayscale-image) x y (method (eql :bicubic)))
>   (interpolate-pixel-cubic image x y #'make-gray
>                            (list #'gray-intensity #'gray-alpha)))
> ```

**Comment by phoe** [comment]
OK - pushing now.

> (a minor flaw that is shifts an image by few pixels, but nevermind ;)

Which direction? Do you mean the `-0.5f0` part?

> Is `ldb` needed here? The value seems to be clamped to the range `[0, width)` or `[0, height)` anyway.

It isn't necessary - the equivalent is to use `the (unsigned-byte 32)` (or even better, `the alex:array-index` ) in order to inform Lisp about the resulting type.

**Comment by phoe** [comment]
Done! Ready for merging.

**Comment by shamazmazum** [comment]
Thanks. Merged. I'll work a bit more on it, fixing some bugs and optimizing for speed

**Comment by phoe** [comment]
OK - thanks a lot. (I'm still curious about the shifting issue that you mentioned though!)

**Comment by shamazmazum** [comment]
> (I'm still curious about the shifting issue that you mentioned though!)

Bicubic mode shifts your image to the down-right corner by 1 pixel or so. You can spot it if you magnify the image a lot and compare with some other iterpolation method. Maybe bicubic interpolator introduces a delay in 1 pixel. I think it's completely OK.

I improved resize with polymorphic-functions. It became a little faster.

**Comment by phoe** [comment]
> Maybe bicubic interpolator introduces a delay in 1 pixel. I think it's completely OK.

I know that there are artifacts on the upper and left edges that quite possibly shouldn't be there. It's very visible when testing on a 5x3 image:
test4

`(imago:resize image 500 300 :interpolation :bicubic)`:
resized

Should this be considered as a bug?

**Comment by shamazmazum** [comment]
> Should this be considered as a bug?

I doubt this is really a bug, it's just a filter delay. But if you manage to remove this delay, I'll merge it

**Comment by phoe** [comment]
> But if you manage to remove this delay, I'll merge it

Nope, I don't think I know how to do that - it might just be a property of the cubic spline that I used, and therefore would require redoing the algorithm. I think it deserves an issue on its own, but I don't think I'll be able to fix it.

**Pull request merged**
